channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - backcall
  - blas
  - ca-certificates
  - certifi
  - configargparse
  - cudatoolkit=11.3
  - dataclasses
  - decorator
  - filelock
  - freetype
  - intel-openmp
  - jedi
  - joblib
  - jpeg
  - lcms2
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuv
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - ninja
  - olefile
  - openssl
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - ptyprocess
  - pygments
  - pytorch==1.12.1
  - pytz
  - pyyaml
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - tabulate
  - threadpoolctl
  - tk
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - tqdm
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - diffdist==0.1
    - strconv==0.4.2

